#!/usr/bin/env sh
set -e

echo "Running terraform fmt..."
terraform -chdir=Lab-A09/infrastructure fmt -check -recursive

echo "Initializing terraform..."
terraform -chdir=Lab-A09/infrastructure init -backend=false -input=false

echo "Running terraform validate..."
terraform -chdir=Lab-A09/infrastructure validate

echo "Running tflint..."
cd Lab-A09/infrastructure
tflint --init
tflint
